-- Track calls made by the score scanner so it can move to the next Gemini
-- model before the project's per-model daily quota is exhausted.
create table public.gemini_model_usage (
  id bigint generated by default as identity primary key,
  model text not null,
  created_at timestamptz not null default now()
);

alter table public.gemini_model_usage enable row level security;

create index gemini_model_usage_model_created_idx
  on public.gemini_model_usage (model, created_at desc);

-- This is called only by the Edge Function with the service-role key. The
-- advisory lock keeps simultaneous scans from reserving the same last slot.
create or replace function public.reserve_gemini_model_request(
  p_model text,
  p_daily_budget integer
)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
  pacific_today date := (now() at time zone 'America/Los_Angeles')::date;
  used integer;
begin
  if p_model is null or btrim(p_model) = '' or p_daily_budget < 1 then
    return false;
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_model || pacific_today::text, 0));
  select count(*) into used
  from public.gemini_model_usage
  where model = p_model
    and (created_at at time zone 'America/Los_Angeles')::date = pacific_today;

  if used >= p_daily_budget then
    return false;
  end if;

  insert into public.gemini_model_usage (model) values (p_model);
  return true;
end;
$$;

revoke all on table public.gemini_model_usage from public, anon, authenticated;
revoke all on sequence public.gemini_model_usage_id_seq from public, anon, authenticated;
revoke all on function public.reserve_gemini_model_request(text, integer)
  from public, anon, authenticated;
grant select, insert on table public.gemini_model_usage to service_role;
grant usage, select on sequence public.gemini_model_usage_id_seq to service_role;
grant execute on function public.reserve_gemini_model_request(text, integer)
  to service_role;
