-- 画像読み取りを認証ユーザーごとに日本時間で1日5回までに制限する。
create table if not exists public.score_scan_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.score_scan_usage enable row level security;

create policy "score_scan_usage_insert_own"
on public.score_scan_usage for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "score_scan_usage_select_own"
on public.score_scan_usage for select
to authenticated
using ((select auth.uid()) = user_id);

create index if not exists score_scan_usage_user_created_idx
on public.score_scan_usage (user_id, created_at desc);

create or replace function public.enforce_daily_score_scan_limit()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  japan_today date := (now() at time zone 'Asia/Tokyo')::date;
  usage_count integer;
begin
  perform pg_advisory_xact_lock(hashtextextended(new.user_id::text || japan_today::text, 0));

  select count(*) into usage_count
  from public.score_scan_usage
  where user_id = new.user_id
    and (created_at at time zone 'Asia/Tokyo')::date = japan_today;

  if usage_count >= 5 then
    raise exception 'daily_scan_limit_exceeded' using errcode = 'P0001';
  end if;
  return new;
end;
$$;

drop trigger if exists enforce_daily_score_scan_limit on public.score_scan_usage;
create trigger enforce_daily_score_scan_limit
before insert on public.score_scan_usage
for each row execute function public.enforce_daily_score_scan_limit();

grant select, insert on public.score_scan_usage to authenticated;
grant usage, select on sequence public.score_scan_usage_id_seq to authenticated;
